version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      DATABASE_URL: mysql://username:password@db_host:db_port/db_name 